[package]
name = "Musettir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm = "0.24"
relm-derive = "0.24"
gtk = "0.16"

[[bin]]
name = "musettir"
path = "src/main.rs"
